-- Fit→free maxes content-fit +'s; free ⋮⋮ uses paintScale; empty-block caret; add-block keeps the line.
-- App/docs marker only; no DDL (frame metadata is JSONB). Remote DDL top: 20260924223511_board_changes_autosave.
