-- Board menus stay through pan/zoom; Sets This board; capture delete; utility titles; Ask composer; Pen arm; minimap inset.
-- App/docs marker only; no DDL. Remote DDL top: 20260914104046_notion_multi_workspace.
