-- Utility + Group/+ Set/+ Presentation rows with organize ⋯ (Capture on Views); calendar connections + set Schedule.
-- App/docs marker only; no DDL. Remote DDL top: 20260914104046_notion_multi_workspace.
